// Code generated by protoc-gen-go. DO NOT EDIT.
// source: user.proto

package userpb // import "github.com/yoheimuta/xo-pb-grpc-example-app/infra/expgenproto/userpb"

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// RegisterUserRequest represents a request for the RegisterUser method.
type RegisterUserRequest struct {
	// user_id represents a user's id. This is UUID v4. Required.
	UserId string `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	// email_address represents an email address. Required.
	EmailAddress string `protobuf:"bytes,2,opt,name=email_address,json=emailAddress,proto3" json:"email_address,omitempty"`
	// password represents a raw password. Required.
	Password             string   `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RegisterUserRequest) Reset()         { *m = RegisterUserRequest{} }
func (m *RegisterUserRequest) String() string { return proto.CompactTextString(m) }
func (*RegisterUserRequest) ProtoMessage()    {}
func (*RegisterUserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_user_5f7732316cf564db, []int{0}
}
func (m *RegisterUserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisterUserRequest.Unmarshal(m, b)
}
func (m *RegisterUserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisterUserRequest.Marshal(b, m, deterministic)
}
func (dst *RegisterUserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterUserRequest.Merge(dst, src)
}
func (m *RegisterUserRequest) XXX_Size() int {
	return xxx_messageInfo_RegisterUserRequest.Size(m)
}
func (m *RegisterUserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterUserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterUserRequest proto.InternalMessageInfo

func (m *RegisterUserRequest) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *RegisterUserRequest) GetEmailAddress() string {
	if m != nil {
		return m.EmailAddress
	}
	return ""
}

func (m *RegisterUserRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

// RegisterUserResponse represents a response for the RegisterUser method.
type RegisterUserResponse struct {
	// auth_token represents a authencation credential.
	AuthToken            string   `protobuf:"bytes,1,opt,name=auth_token,json=authToken,proto3" json:"auth_token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RegisterUserResponse) Reset()         { *m = RegisterUserResponse{} }
func (m *RegisterUserResponse) String() string { return proto.CompactTextString(m) }
func (*RegisterUserResponse) ProtoMessage()    {}
func (*RegisterUserResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_user_5f7732316cf564db, []int{1}
}
func (m *RegisterUserResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisterUserResponse.Unmarshal(m, b)
}
func (m *RegisterUserResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisterUserResponse.Marshal(b, m, deterministic)
}
func (dst *RegisterUserResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterUserResponse.Merge(dst, src)
}
func (m *RegisterUserResponse) XXX_Size() int {
	return xxx_messageInfo_RegisterUserResponse.Size(m)
}
func (m *RegisterUserResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterUserResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterUserResponse proto.InternalMessageInfo

func (m *RegisterUserResponse) GetAuthToken() string {
	if m != nil {
		return m.AuthToken
	}
	return ""
}

func init() {
	proto.RegisterType((*RegisterUserRequest)(nil), "userpb.RegisterUserRequest")
	proto.RegisterType((*RegisterUserResponse)(nil), "userpb.RegisterUserResponse")
}

func init() { proto.RegisterFile("user.proto", fileDescriptor_user_5f7732316cf564db) }

var fileDescriptor_user_5f7732316cf564db = []byte{
	// 218 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x54, 0x8f, 0x31, 0x4b, 0xc4, 0x40,
	0x10, 0x85, 0x39, 0x85, 0xd3, 0x1b, 0xb4, 0x59, 0x05, 0x83, 0x20, 0xc8, 0xd9, 0xd8, 0xe4, 0xb6,
	0x10, 0x6b, 0x39, 0x3b, 0xdb, 0xa0, 0x8d, 0x4d, 0x98, 0xb8, 0x63, 0xb2, 0x78, 0xc9, 0x8c, 0x3b,
	0xbb, 0x18, 0xff, 0xbd, 0xec, 0x9e, 0x08, 0x76, 0xef, 0x7d, 0xef, 0xc1, 0xe3, 0x01, 0x24, 0xa5,
	0xb0, 0x91, 0xc0, 0x91, 0xcd, 0x32, 0x6b, 0xe9, 0xd6, 0x0c, 0x67, 0x0d, 0xf5, 0x5e, 0x23, 0x85,
	0x17, 0xa5, 0xd0, 0xd0, 0x67, 0x22, 0x8d, 0xe6, 0x02, 0x8e, 0x72, 0xa1, 0xf5, 0xae, 0x5a, 0x5c,
	0x2f, 0x6e, 0x57, 0x4d, 0xe9, 0x3f, 0x39, 0x73, 0x03, 0xa7, 0x34, 0xa2, 0xdf, 0xb5, 0xe8, 0x5c,
	0x20, 0xd5, 0xea, 0xa0, 0xc4, 0x27, 0x05, 0x6e, 0xf7, 0xcc, 0x5c, 0xc2, 0xb1, 0xa0, 0xea, 0x17,
	0x07, 0x57, 0x1d, 0x96, 0xfc, 0xcf, 0xaf, 0xef, 0xe1, 0xfc, 0xff, 0xa0, 0x0a, 0x4f, 0x4a, 0xe6,
	0x0a, 0x00, 0x53, 0x1c, 0xda, 0xc8, 0x1f, 0x34, 0xfd, 0x8e, 0xae, 0x32, 0x79, 0xce, 0xe0, 0x71,
	0xfb, 0xfa, 0xd0, 0xfb, 0x38, 0xa4, 0x6e, 0xf3, 0xc6, 0xa3, 0xfd, 0xe6, 0x81, 0xfc, 0x98, 0x22,
	0xda, 0x99, 0x6b, 0xe9, 0x6a, 0x9a, 0x71, 0x94, 0x1d, 0xd5, 0x28, 0x62, 0xfd, 0xf4, 0x1e, 0xd0,
	0xd2, 0x2c, 0x3d, 0x4d, 0xe5, 0xab, 0xdd, 0x5f, 0xed, 0x96, 0xc5, 0xdd, 0xfd, 0x04, 0x00, 0x00,
	0xff, 0xff, 0x3a, 0x0f, 0x25, 0xea, 0x07, 0x01, 0x00, 0x00,
}
