// Code generated by protoc-gen-go. DO NOT EDIT.
// source: userproduct.proto

package userproductpb // import "github.com/yoheimuta/xo-pb-grpc-example-app/infra/expgenproto/userproductpb"

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// ListUserProductRequest represents a request for the ListUserProduct method.
type ListUserProductRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListUserProductRequest) Reset()         { *m = ListUserProductRequest{} }
func (m *ListUserProductRequest) String() string { return proto.CompactTextString(m) }
func (*ListUserProductRequest) ProtoMessage()    {}
func (*ListUserProductRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_userproduct_0af195eec7d3f12d, []int{0}
}
func (m *ListUserProductRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListUserProductRequest.Unmarshal(m, b)
}
func (m *ListUserProductRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListUserProductRequest.Marshal(b, m, deterministic)
}
func (dst *ListUserProductRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListUserProductRequest.Merge(dst, src)
}
func (m *ListUserProductRequest) XXX_Size() int {
	return xxx_messageInfo_ListUserProductRequest.Size(m)
}
func (m *ListUserProductRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListUserProductRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListUserProductRequest proto.InternalMessageInfo

// ListUserProductResponse represents a response for the ListUserProduct method.
type ListUserProductResponse struct {
	// products represents a list of product.
	Products             []*ListUserProductResponse_Product `protobuf:"bytes,1,rep,name=products,proto3" json:"products,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                           `json:"-"`
	XXX_unrecognized     []byte                             `json:"-"`
	XXX_sizecache        int32                              `json:"-"`
}

func (m *ListUserProductResponse) Reset()         { *m = ListUserProductResponse{} }
func (m *ListUserProductResponse) String() string { return proto.CompactTextString(m) }
func (*ListUserProductResponse) ProtoMessage()    {}
func (*ListUserProductResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_userproduct_0af195eec7d3f12d, []int{1}
}
func (m *ListUserProductResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListUserProductResponse.Unmarshal(m, b)
}
func (m *ListUserProductResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListUserProductResponse.Marshal(b, m, deterministic)
}
func (dst *ListUserProductResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListUserProductResponse.Merge(dst, src)
}
func (m *ListUserProductResponse) XXX_Size() int {
	return xxx_messageInfo_ListUserProductResponse.Size(m)
}
func (m *ListUserProductResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListUserProductResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListUserProductResponse proto.InternalMessageInfo

func (m *ListUserProductResponse) GetProducts() []*ListUserProductResponse_Product {
	if m != nil {
		return m.Products
	}
	return nil
}

// Product represents an user's product.
type ListUserProductResponse_Product struct {
	// user_product_id represents a product id. This is UUID v4.
	UserProductId string `protobuf:"bytes,1,opt,name=user_product_id,json=userProductId,proto3" json:"user_product_id,omitempty"`
	// title represents a title.
	Title string `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	// description represents a description.
	Description          string   `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListUserProductResponse_Product) Reset()         { *m = ListUserProductResponse_Product{} }
func (m *ListUserProductResponse_Product) String() string { return proto.CompactTextString(m) }
func (*ListUserProductResponse_Product) ProtoMessage()    {}
func (*ListUserProductResponse_Product) Descriptor() ([]byte, []int) {
	return fileDescriptor_userproduct_0af195eec7d3f12d, []int{1, 0}
}
func (m *ListUserProductResponse_Product) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListUserProductResponse_Product.Unmarshal(m, b)
}
func (m *ListUserProductResponse_Product) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListUserProductResponse_Product.Marshal(b, m, deterministic)
}
func (dst *ListUserProductResponse_Product) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListUserProductResponse_Product.Merge(dst, src)
}
func (m *ListUserProductResponse_Product) XXX_Size() int {
	return xxx_messageInfo_ListUserProductResponse_Product.Size(m)
}
func (m *ListUserProductResponse_Product) XXX_DiscardUnknown() {
	xxx_messageInfo_ListUserProductResponse_Product.DiscardUnknown(m)
}

var xxx_messageInfo_ListUserProductResponse_Product proto.InternalMessageInfo

func (m *ListUserProductResponse_Product) GetUserProductId() string {
	if m != nil {
		return m.UserProductId
	}
	return ""
}

func (m *ListUserProductResponse_Product) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *ListUserProductResponse_Product) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func init() {
	proto.RegisterType((*ListUserProductRequest)(nil), "userproductpb.ListUserProductRequest")
	proto.RegisterType((*ListUserProductResponse)(nil), "userproductpb.ListUserProductResponse")
	proto.RegisterType((*ListUserProductResponse_Product)(nil), "userproductpb.ListUserProductResponse.Product")
}

func init() { proto.RegisterFile("userproduct.proto", fileDescriptor_userproduct_0af195eec7d3f12d) }

var fileDescriptor_userproduct_0af195eec7d3f12d = []byte{
	// 241 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x90, 0xcb, 0x4a, 0x03, 0x31,
	0x14, 0x86, 0x19, 0x8b, 0xb7, 0x14, 0x11, 0x83, 0x68, 0x70, 0x35, 0x74, 0x21, 0xdd, 0x4c, 0x02,
	0xfa, 0x06, 0xee, 0xbc, 0x81, 0x14, 0xdc, 0xb8, 0x29, 0x73, 0x39, 0x4e, 0x0f, 0x74, 0x26, 0xc7,
	0xe4, 0x04, 0xc6, 0xb7, 0xf4, 0x91, 0xc4, 0x34, 0x4a, 0x07, 0xe9, 0xf2, 0xff, 0xbe, 0xfc, 0x3f,
	0x49, 0xc4, 0x59, 0xf0, 0xe0, 0xc8, 0xd9, 0x26, 0xd4, 0xac, 0xc9, 0x59, 0xb6, 0xf2, 0x64, 0x0b,
	0x51, 0x35, 0x53, 0xe2, 0xe2, 0x09, 0x3d, 0xbf, 0x7a, 0x70, 0x2f, 0x1b, 0xb8, 0x80, 0x8f, 0x00,
	0x9e, 0x67, 0x5f, 0x99, 0xb8, 0xfc, 0xa7, 0x3c, 0xd9, 0xde, 0x83, 0x7c, 0x10, 0x47, 0x69, 0xc2,
	0xab, 0x2c, 0x9f, 0xcc, 0xa7, 0x37, 0x5a, 0x8f, 0x76, 0xf5, 0x8e, 0xa6, 0xfe, 0xcd, 0x7f, 0xfd,
	0x2b, 0x14, 0x87, 0x09, 0xca, 0x6b, 0x71, 0xfa, 0xb3, 0xb2, 0x4c, 0x6e, 0x89, 0x8d, 0xca, 0xf2,
	0x6c, 0x7e, 0xbc, 0x88, 0x97, 0x4e, 0xa7, 0xee, 0x1b, 0x79, 0x2e, 0xf6, 0x19, 0x79, 0x0d, 0x6a,
	0x2f, 0xda, 0x4d, 0x90, 0xb9, 0x98, 0x36, 0xe0, 0x6b, 0x87, 0xc4, 0x68, 0x7b, 0x35, 0x89, 0x6e,
	0x1b, 0xdd, 0x3d, 0xbf, 0x3d, 0xb6, 0xc8, 0xab, 0x50, 0xe9, 0xda, 0x76, 0xe6, 0xd3, 0xae, 0x00,
	0xbb, 0xc0, 0xa5, 0x19, 0x6c, 0x41, 0x55, 0xd1, 0x3a, 0xaa, 0x0b, 0x18, 0xca, 0x8e, 0xd6, 0x50,
	0x94, 0x44, 0x06, 0xfb, 0x77, 0x57, 0x1a, 0x18, 0xa8, 0x85, 0x3e, 0x7e, 0x9e, 0x19, 0xbd, 0xb1,
	0x3a, 0x88, 0xf0, 0xf6, 0x3b, 0x00, 0x00, 0xff, 0xff, 0x1d, 0xd7, 0xb6, 0x6d, 0x66, 0x01, 0x00,
	0x00,
}
